server:
  port: 8181

spring:
  application:
    name: currency_microservice
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:currency_microservice
    username: sa
    password: admin
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: true
  jpa:
    show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
    ddl-auto: none
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    enabled: true
    drop-first: false
    default-schema: public

